modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/JAD3N/mc-wrench/issues"

[[mods]]
modId="wrench"
version="${file.jarVersion}"
displayName="Wrench"
# updateJSONURL="https://raw.githubusercontent.com/JAD3N/mc-wrench/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wrench"
authors="JAD3N"
description='''
Adds the ability to rotate blocks in Minecraft using a wrench.
'''

[[dependencies.wrench]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wrench]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
